baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[params]
    ShowBreadcrumbs = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
[params.cover]
    linkFullImages = true
[params.homeInfoParams]
    Title = "Hello stranger"
    Content = "Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff."
[[params.socialIcons]]
    name = "facebook"
    url = "https://facebook.com/"
[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/"





[menu]
[[menu.main]]
  identifier = 'categories'
  name = 'Categories'
  url = '/categories/'
  weight = -110
[[menu.main]]
  identifier = 'tags'
  name = 'Tags'
  url = '/tags/'
  weight = -100
  [[menu.main]]
  identifier = 'archives'
  name = 'Archives'
  url = '/archives/'
  weight = -90
  